### PR TITLE
updated signup page added persistent session storage fixed issue with not being ...

### PR DESCRIPTION
**Pull request by germainep**

### CODE REVIEW

**Comment by aldraco** [comment]
I like the idea of letting users put in a "real" name instead of a username, that's more professional and probably a better idea in the setting that this app will be used.

What are the third and fourth twitter keys for?

The user.editProfile controller is redundant; the one that is there has the same functionality. _.assign takes all of the fields from the req.body and adds them to the item if they are not already there.

**Comment by germainep** [comment]
I wasn't familar with _.assign but I will revise if I can get it to work but I'm also considering moving that function to angular after I work out the layout for the profile page also since we are using a real name does it need to be edited

**Comment by germainep** [comment]
for the export.update controller is there any thing other than updating the database via the profile edit page that it needs to do because if it is redundant  and not working I think that's the function that needs to be removed

**Comment by aldraco** [comment]
Re: moving things to Angular - you don't have to move anything to use that data or function, you can use an $http service to get data from the backend and to send it back. Angular just deals with display logic, so to maintain our separation of concerns, I think we should keep any database-related functions where they are for now.

**Comment by aldraco** [comment]
export.update isn't being used for anything else at the moment, but because of _.assign it _can_ be used to change anything on the User model we want. Assign doesn't depend on the function specifying any fields, and it also doesn't require any fields to be filled out. It just takes the new data from the body, whatever it is, and makes changes. 

So, the question I guess we need to figure out an answer to is what else are we going to change on the User model, and do we need separate functions for all of those things (i.e. one for the profile, one for updating contact information, etc) or can we just use one flexible function to do all of it? It would be less redundant to use one function for everything, but one could also argue that keeping lots of separate functions would limit what can be changed on the user model - and that could be a good thing for security. Probably a good discussion to have.

**Comment by aldraco** [comment]
Actually - looking again, the user is the only one that can edit their own profile, since their own userid is pulled from the session. That makes more sense than allowing a user to edit other users ... which could be disastrous!  I think you're absolutely right about the edit profile function needing to be separate, and not part of the API at all.

**Pull request merged**
