### PR TITLE
Removed GET /api/meetings todo

### PR DESCRIPTION
**Pull request by ghost**
> TODO - This should return only meetings that the current, logged-in user is a member of (called through a populated user.meetings array).

Since this was updated with #50

### CODE REVIEW

**Comment by aldraco** [comment]
It actually still says that it returns all the meetings in the database. Could you change it to reflect that it now just calls for meetings that the user is a member of?

**Comment by ghost** [comment]
Updated.

Also while were looking at the file. Are any of the other TODOs completed?

I was looking at this one:

> [TODO add contact information to user model]

It looks like there is contact information in the model (email) but I'm not sure if that's what was meant.

**Comment by aldraco** [comment]
@jameskopacz the email address that is currently in the model (local.email) is for login/validation purposes.

**Comment by aldraco** [comment]
this looks good to me.

**Comment by aldraco** [comment]
I'll have to check on he other to do s but a few of these methods may change ever so slightly in reference to some comments from Bianca. This is great for now.

**Pull request merged**
